# -*- coding: utf-8 -*-
"""UnemploymentinIndia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bj-BMVTtORByL3X7u4-Iv5bnKKyBG35R
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data=pd.read_csv('/content/Unemployment in India.csv')
data=pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')
print(data.head())

print(data.isnull().sum())

data.columns

from matplotlib.pyplot import style

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

data.columns=['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Region.1', 'longitude', 'latitude']
plt.title('Indian Unemployment')
sns.histplot(x=' Estimated Employed',hue='Region',data=data)
plt.show()

plt.figure(figsize=(12,10))
plt.title('Indian Unemployment')
sns.histplot(x=' Estimated Employed',hue='Region',data=data)
plt.show()

unemployment=data[['Region', ' Estimated Unemployment Rate (%)']]
figure=px.sunburst(unemployment,path=['Region'],values=' Estimated Unemployment Rate (%)',width=700,height=700,color_continuous_scale='rdY1Gn',title='Unemployment in India')
figure.show()

